name: CREATE MINOR RELEASE

on:
  push:
    branches:
      - master

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-current-version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Current Version
        id: get-current-version
        run: |
          version=$(curl --silent --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/tags" | jq -r '.[0].name')
          echo "::set-output name=version::$version"

  bump-minor:
    needs: get-version
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.update-version.outputs.newVersion }}
    steps:
      - name: Update Version
        id: update-version
        run: |
          version="${{ needs.get-version.outputs.version }}"
          IFS='.' read -ra versionArray <<< "$version"
          majorVersion="${versionArray[0]}"
          minorVersion="${versionArray[1]}"
          patchVersion="${versionArray[2]}"

          patchVersion=$((patchVersion + 1))

          newVersion="$majorVersion.$minorVersion.$patchVersion"
          echo "::set-output name=newVersion::$newVersion"
          echo "Bumping to: $newVersion"
          

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.update-version.outputs.newVersion }}
          release_name: Release ${{ steps.update-version.outputs.newVersion }}
          draft: false
          prerelease: false  