name: DEPLOY TO BETA

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Version
        id: getVersion
        run: |
          version=$(curl --silent --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/tags" | jq -r '.[0].name')

          IFS='.' read -ra versionArray <<< "$version"
          
          majorVersion="${versionArray[0]}"
          minorVersion="${versionArray[1]}"
          patchVersion="${versionArray[2]}"
          patchVersion=$((patchVersion + 1))

          newVersion="$majorVersion.$minorVersion.$patchVersion"

          echo "::set-output name=newVersion::$newVersion"

      - name: Update Version
        run: |
          version="${{ steps.getVersion.outputs.newVersion }}"
          echo "$version"                             

      - name: Deploy to Beta Environment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.BETA_FTP_SERVER }}
          username: ${{ secrets.BETA_FTP_USERNAME }}
          password: ${{ secrets.BETA_FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.BETA_SERVER_DIR }}
