name: FTP Upload
'on':
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update version
        uses: datamonsters/replace-action
        with:
          files: file.txt
          replacements: 'Version:     1.0.0,Version:     abc'