name: FTP Upload
'on':
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Update version
        run: sed -i 's/Version:     1.0.0/Version:     abc/g' file.txt